#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop then if 9 prints hi
i=1
while [ $i -le 10 ]; do
	echo "Best School"
	if [ $i -eq 9 ]; then
		echo "Hi"
	fi
	i=$((i + 1))
done
