#!/usr/bin/env bash
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

i=1
while [ $i -le 10 ]; do
	echo "Best School"
	if [ $i -eq 4 ]; then
		echo "good luck"
	elif [ $i -eq 8 ]; then
		echo "bad luck"
	fi
	i=$((i + 1))
done
