#!/usr/bin/env bash
#Write a Bash script that displays:
#The content of the current directory
#In a list formats
#Where only the part of the name after the first dash is displayed

for i in $(ls); do
  IFS="-" read -ra parts <<< "$i"  # Split $i using "-" as the separator
  echo "${parts[1]}"
done
