#!/usr/bin/env bash
#Write a Bash script that displays:
#The content of the current directory
#In a list formats
#Where only the part of the name after the first dash is displayed

for list in *; do
	if [[ $list == *-* ]]; then
		IFS="-" read -ra parts <<< "$list"
		echo "${parts[1]}"
	else
		echo "$list"
	fi
done
